#ifndef ACCELEROMETER_H
#define ACCELEROMETER_H

#include "main.h"

#define ACCELEROMETER_ADDR (0x1C << 1)
#define ACCELEROMETER_REG_OUT_X_MSB 0x01
#define ACCELEROMETER_REG_WHO_AM_I 0x0D
#define ACCELEROMETER_REG_CTRL_REG1 0x2A
#define ACCELEROMETER_WHO_AM_I_VALUE 0x2A
#define ACCELEROMETER_I2C_TIMEOUT_MS 100U
#define ACCELEROMETER_AXIS_THRESHOLD 3000
#define ACCELEROMETER_ROTATION_STABLE_TIME_MS 500U
#define ACCELEROMETER_REG_PULSE_CFG 0x21
#define ACCELEROMETER_REG_PULSE_SRC 0x22
#define ACCELEROMETER_REG_PULSE_THSX 0x23
#define ACCELEROMETER_REG_PULSE_THSY 0x24
#define ACCELEROMETER_REG_PULSE_THSZ 0x25
#define ACCELEROMETER_REG_PULSE_TMLT 0x26
#define ACCELEROMETER_REG_PULSE_LTCY 0x27
#define ACCELEROMETER_REG_PULSE_WIND 0x28

typedef enum {
  DISPLAY_ROTATION_0,
  DISPLAY_ROTATION_90,
  DISPLAY_ROTATION_180,
  DISPLAY_ROTATION_270,
} DisplayRotation;

HAL_StatusTypeDef Accelerometer_Init(void);
DisplayRotation Accelerometer_GetRotation(void);
HAL_StatusTypeDef Accelerometer_EnableTapDetection(void);
uint8_t Accelerometer_TapDetected(void);

#endif